version: '3.8'

services:
  quiz-game:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    command: >
      sh -c "python load_data.py &&
             flask run --host=0.0.0.0"
