version: '3.8'

services:
  quiz-game:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    command: >
      sh -c "python initial_data.py ./data/questions.json &&
             flask run --host=0.0.0.0"
